controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    prismatic_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      # type: position_controllers/GripperActionController
      # type: effort_controllers/JointGroupEffortController
      # type: forward_command_controller/ForwardCommandController

    gripper_action_controller:
          type: position_controllers/GripperActionController      

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

prismatic_controller:
  ros__parameters:
    joints:
      - base_rail_to_ mid_rail_joint
      - mid_rail_to_arm_car_joint
    command_interfaces:
       - position
    state_interfaces:
       - position
      # - velocity

arm_controller:
  ros__parameters:
    joints:
      - arm_base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      # - velocity

gripper_controller:
  ros__parameters:
    joints:
      # - wrist_joint
      - gripper_right_joint
    command_interfaces:
      - position
      # - effort
    state_interfaces:
      - position
      # - effort
      # - velocity

    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: true      

gripper_action_controller:
  ros__parameters:
    joints: 
      - gripper_right_joint
    action_monitor_rate: 50.0
    goal_tolerance: 0.01
    max_effort: 100.0
    allow_stalling: false
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0      